local t = require('test-env')
local ERRORS = require('error_handling')
local vesper = require('vesper')
local EV = require('events')

local uuid = require('uuid').uuid;

t.wait_events({TabTitleChanged = 1}, function()
    assert(#vesper.get_terminals() == 1, "We should have only one terminal")
    local sel = t.action_shortcut('select_command')
    local term = vesper.get_current_terminal()
    t.simulate_keys(sel, {CommandPaletteOpen = 1}, function()
        t.simulate_keys('O p e n <cr>', {PaneChanged = 1}, function()
            assert(#vesper.get_terminals() == 2, "We should have 2 terminals now")
            assert(vesper.get_current_terminal().term_id ~= term.term_id, 'We should be on the second terminal')
            t.simulate_keys(sel, {CommandPaletteOpen = 1}, function()
                t.simulate_keys('<C-c>', {CommandPaletteClosed = 1}, function()
                    t.simulate_keys(sel, {CommandPaletteOpen = 1}, function()
                        t.simulate_keys('S e l e c t T a b <cr>', {UserInputPrompt = 1}, function()
                            t.simulate_keys('1 <cr>', {PaneChanged = 1}, function()
                                assert(vesper.get_current_terminal().term_id == term.term_id, 'We should be on the first terminal now')
                                t.done()
                            end)
                        end)
                    end)
                end)
            end)
        end)
    end)
end)
