local t = require('test-env')
local vesper = require('vesper')
local files = require('files')

local assert = function(n)
    local terms = vesper.get_terminals()
    t.assert(#terms == n, "There should be " .. n .. " opened tabs")
end

t.wait_events({TabTitleChanged = 1}, function()
    t.simulate_keys(t.action_shortcut('create_float'), {PaneChanged = 1}, function()
        assert(2)
        files.write_file(t.get_root() .. '/config/config.ini', '[Options]\n\nmodifier = <C-b>')
        t.wait_events({ConfigReloaded = 1}, function()
            t.simulate_keys('<C-s> <C-b> c', {PaneChanged = 1}, function()
                assert(3)
                t.done()
            end)
        end)
        require('config').reload_config()
    end)
end)
