local t = require('test-env')
local azul = require('azul')

local main_t = azul.get_current_terminal()
print(vim.inspect(main_t.buf))
t.simulate_keys('<C-s>sljjj<cr>')
vim.fn.timer_start(1, function()
    local n = #azul.get_terminals()
    t.assert(n == 5, "There should be 5 terminals, not " .. vim.inspect(n))
    t.single_shot('PaneChanged', function(args)
        t.assert(args[1] == main_t, "The current selected terminal should be " .. main_t.buf .. ", not " .. args[1].buf)
        t.single_shot('PaneChanged', function()
            t.single_shot('Error', function()
                -- There is an error message that should be clicked
                t.simulate_keys('<cr>')
                n = #azul.get_terminals()
                t.assert(n == 6, "There should be 6 terminals, not " .. vim.inspect(n))
                t.done()
            end)
            -- This should generate an error, since we cannot split while in floating mode
            t.simulate_keys('<C-s>sl')
        end)
        t.simulate_keys('<C-s>f')
    end)
    t.simulate_keys('<C-s>ph<cr>')
end)
