local core = require('core')
local session = require('session')
local funcs = require('functions')
local EV = require('events')
local U = require('undo')
local F = require('floats')
local R = require('remote')
local MAP = require('mappings')

local M = {}

M.is_float = funcs.is_float
M.debug = core.debug
M.get_current_terminal = core.get_current_terminal
M.open = core.open
M.enter_mode = core.enter_mode
M.hide_floats = F.hide_floats
M.show_floats = F.show_floats
M.are_floats_hidden = function(group)
    return funcs.are_floats_hidden(group, core.get_terminals())
end
M.open_float = F.open_float
M.toggle_floats = F.toggle_floats
M.feedkeys = core.feedkeys
M.remove_key_map = core.remove_key_map
M.set_key_map = core.set_key_map
M.get_terminals = core.get_terminals
M.move_current_float = F.move_current_float
M.select_pane = core.select_pane
M.select_next_pane = core.select_next_pane
M.current_mode = core.current_mode
M.send_to_buf = core.send_to_buf
M.send_to_current = core.send_to_current
M.split = core.split
M.position_current_float = F.position_current_float
M.redraw = core.redraw
M.set_workflow = core.set_workflow
M.suspend = core.suspend
M.resume = core.resume
M.resize = core.resize
M.disconnect = core.disconnect
M.save_layout = session.save_layout
M.restore_layout = session.restore_layout
M.set_win_id = core.set_win_id
M.set_tab_variable = core.set_tab_variable
M.set_cmd = core.set_cmd
M.get_current_workflow = core.get_current_workflow
M.paste_from_clipboard = core.paste_from_clipboard
M.start_logging = core.start_logging
M.stop_logging = core.stop_logging
M.toggle_passthrough = core.toggle_passthrough
M.rotate_panel = core.rotate_panel
M.on = EV.on
M.clear_event = EV.clear_event
M.get_mode_mappings = core.get_mode_mappings
M.user_input = core.user_input
M.get_file = core.get_file
M.rename_tab = core.rename_tab
M.rename_floating_pane = F.rename_floating_pane
M.rename_current_tab = core.rename_current_tab
M.rename_current_pane = F.rename_current_pane
M.edit = core.edit
M.edit_scrollback = core.edit_scrollback
M.edit_scrollback_log = core.edit_scrollback_log
M.edit_current_scrollback = core.edit_current_scrollback
M.edit_current_scrollback_log = core.edit_current_scrollback_log
M.get_current_modifier = core.get_current_modifier
M.is_modifier_mode = core.is_modifier_mode
M.select_tab = core.select_tab
M.create_tab = core.create_tab
M.create_tab_remote = R.create_tab_remote
M.on_action = EV.on_action
M.open_remote = R.open_remote
M.remote_reconnect = R.remote_reconnect
M.remote_quit = R.remote_quit
M.open_float_remote = R.open_float_remote
M.split_remote = R.split_remote
M.remote_enter_scroll_mode = R.remote_enter_scroll_mode
M.remote_state = funcs.remote_state
M.persistent_on = EV.persistent_on
M.single_shot = EV.single_shot
M.undo = U.undo
M.toggle_fullscreen = F.toggle_fullscreen

M.cd = core.cd
M.find_key_map = core.find_key_map
M.add_key_parser = MAP.add_key_parser
M.remote_exit_scroll_mode = R.remote_exit_scroll_mode
M.register_remote_profile = R.register_remote_profile

return M
